<?php

namespace app\admin\controller;

use think\Controller;
use think\Db;

class Admin extends Controller
{
    protected $user = null;

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->user = session('adminuser');

        if (empty($this->user)) {
            $this->redirect('Login/index');
        }
    }

    /****
     * 获取分页数据
     * @param $sql  string  要查询的sql
     * @param $row  int 每页条数
     * @param $p   int  当前页
     * @return array  分页数据
     */
    protected function getPage($sql, $row, $p)
    {
        $c             = Db::query('select count(*) as c from (' . $sql . ') as a');
        $c             = array_shift($c);
        $c             = isset($c['c']) ? $c['c'] : 0;
        $page          = [];
        $page['count'] = $c;
        $page['curr']  = $p;
        $page['cPage'] = ceil($c / $row);
        $page['isEnd'] = $page['cPage'] == $p ? 1 : 0;
        return $page;
    }


}
