<?php

namespace app\index\controller;

use think\Controller;
use think\Db;

class News extends Controller
{


    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $token = input('token');


    }

    /***
     * 空操作方法
     * @param $name
     * @return mixed
     */
    public function _empty($name)

    {

        return $this->fetch('error/index');

    }

    //新闻
    public function lists()
    {
        $type  = input('type');
        $type  = empty($type) ? 1 : $type;
        $lists = db('news')
            ->where('type', $type)
            ->order('id desc')
            ->paginate(5);
        return json(['code' => 0, 'msg' => '新闻列表', 'data'=>$lists]);
    }

}
